blank_issues_enabled: false
contact_links:
    - name: Kernixcord Support Server
      url: https://discord.gg/kernix
      about: If you need help regarding Kernixcord, please join our support server!
    - name: Kernixcord Installer
      url: https://github.com/kanvekin/Privxe
      about: You can find the Kernixcord Installer here
